# Generated by Django 3.0 on 2019-12-20 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191220_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token', to='accounts.KakaoAccounts'),
        ),
    ]
