# Generated by Django 3.0 on 2020-02-18 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_token_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
