# Generated by Django 3.0 on 2020-02-20 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='thumbnail_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='썸네일 이미지 주소'),
        ),
    ]
