# Generated by Django 3.0 on 2020-02-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20200220_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='number',
        ),
    ]
