# Generated by Django 3.0 on 2020-02-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_remove_song_number'),
        ('play_lists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playlist',
            options={'verbose_name': '플레이 리스트', 'verbose_name_plural': '플레이 리스트'},
        ),
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, null=True, to='songs.Song'),
        ),
    ]
