# Generated by Django 3.0 on 2020-02-25 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_remove_song_number'),
        ('play_lists', '0002_auto_20200225_0435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='songs.Song'),
        ),
    ]
